server:
  port: 4004

spring:
  cloud:
    gateway:
      routes:
        ## REST CLIENT -> http://localhost:4004/api/patients
        ## API GATEWAY -> http://patient-service:4000/patients
        ## PATIENT SERVICE (SPRING BOOT APP) -> /patient -> Patients Array
        - id: patient-service-route
          uri: http://patient-service:4000
          predicates:
            - Path=/api/patients,/api/patients/**
          filters:
            - StripPrefix=1

        ## REST-CLIENT -> http://localhost:4004/api-docs/patients
        ## API-GATEWAY -> http://patient-service:4000/v3/api-docs
        - id: api-docs-patient-route
          uri: http://patient-service:4000
          predicates:
            - Path=/api-docs/patients
          filters:
            - RewritePath=/api-docs/patients,/v3/api-docs